# Yggdrasil recipe for `Ajt_jll` — the file to open as a pull request against
# https://github.com/JuliaPackaging/Yggdrasil, under `A/Ajt/`.
#
# It is kept in this repository, not only in that one, because it has to move
# with `build.zig.zon`: the Zig version, the libgit2 pin and the version string
# are all facts about this tree, and a recipe that lives only in Yggdrasil goes
# stale the first time one of them changes.
#
# # Why this looks unlike its neighbours
#
# A normal recipe calls `./configure && make` with BinaryBuilder's `${CC}`.
# Ajt is built by Zig, and Zig is its own cross-compiler, so the toolchain comes
# in as a source and does the targeting itself. Two consequences drive the rest
# of this file:
#
#   * **The sandbox has no network, and `libgit2` is a *lazy* dependency.**
#     `zig build -Dgit` would fetch it, which cannot happen here, so the pinned
#     tarball arrives as a source and is placed in the Zig package cache by
#     `zig fetch` before the build runs. That is not a workaround for the
#     laziness, it is the point of it: a machine that only builds the pure-Zig
#     half never needs the network at all.
#   * **BinaryBuilder's triplets are not Zig's.** `x86_64-apple-darwin20` is
#     `x86_64-macos` to Zig, and so on, so the mapping is explicit below rather
#     than implied.
#
# # Status
#
# **This builds.** Verified locally for `x86_64-linux-musl`, producing
# `Ajt.v0.1.0.x86_64-linux-musl.tar.gz`; the three questions that decide whether
# the approach works at all were each answered by a run rather than by reading:
#
#   * `zig fetch <checkout>` reproduces
#     `N-V-__8AAPAkMAHF73yNJSpdsQlf-mNs4jTb0NHpLoiNRzOw`, the hash
#     build.zig.zon pins for the tarball — so a `GitSource` satisfies both
#     BinaryBuilder's refusal of GitHub's auto-generated archives and the pin.
#     The checkout must have its `.git` removed first, which the script does and
#     the assertion below caught.
#   * `zig build -Dgit` completes with the sandbox offline once that hash is in
#     `ZIG_GLOBAL_CACHE_DIR`, which is the whole offline question.
#   * Zig runs unmodified inside BinaryBuilder's musl rootfs.
#
# What remains is the part that is not code: opening the pull request against
# Yggdrasil, and waiting for `Ajt_jll` to be built and registered. Until that
# exists, `julia/Artifacts.toml` — generated by `packaging/gen_artifacts.jl`
# from the GitHub release — is what delivers the binary, and switching over is a
# change to `Ajt._bundled_binary` alone.
#
# Running it locally:
#
#     julia --project=. build_tarballs.jl --verbose --debug x86_64-linux-musl
#
# On NixOS that must be wrapped in `steam-run` (or any FHS user environment):
# BinaryBuilder's own helper binaries are dynamically linked against
# `/lib64/ld-linux-x86-64.so.2`, which does not exist there. Yggdrasil's CI is
# Ubuntu and needs no such wrapper.

using BinaryBuilder, Pkg

name = "Ajt"
# Must match `.version` in build.zig.zon, which is the only place it is written.
version = v"0.1.0"

sources = [
    GitSource("https://github.com/sinisterMage/Ajt.jl.git", "0000000000000000000000000000000000000000"),
    ArchiveSource(
        "https://ziglang.org/download/0.16.0/zig-x86_64-linux-0.16.0.tar.xz",
        "70e49664a74374b48b51e6f3fdfbf437f6395d42509050588bd49abe52ba3d00",
        unpack_target = "zig",
    ),
    # Pinned in build.zig.zon, and asserted again at runtime by
    # `git_libgit2_version` — `src/git/c.zig` is hand-written `extern`
    # declarations over libgit2's structs, so a moved field is a function
    # pointer called with the wrong arguments rather than a link error.
    #
    # A `GitSource` although build.zig.zon names a tarball, for two reasons that
    # happen to agree. BinaryBuilder refuses GitHub's auto-generated archives
    # outright — their checksums are not promised to be stable — and it is
    # right to. And it costs nothing here: Zig hashes the *unpacked tree*, so
    # this checkout and that tarball produce the same
    # `N-V-__8AAPAkMAHF73yNJSpdsQlf-mNs4jTb0NHpLoiNRzOw`, which is what the
    # `zig fetch` below relies on and what makes the pin still a pin.
    GitSource(
        "https://github.com/libgit2/libgit2.git",
        "0060d9cf5666f015b1067129bd874c6cc4c9c7ac",  # v1.9.1
    ),
]

script = raw"""
set -eu
cd "${WORKSPACE}/srcdir"

export PATH="${WORKSPACE}/srcdir/zig/zig-x86_64-linux-0.16.0:${PATH}"
export ZIG_GLOBAL_CACHE_DIR="${WORKSPACE}/srcdir/zig-cache"
mkdir -p "${ZIG_GLOBAL_CACHE_DIR}"

# BinaryBuilder's triplet -> Zig's. Anything unlisted is a target this recipe
# has not been taught, and failing here beats building for the wrong one.
case "${target}" in
    x86_64-linux-gnu)     ZIG_TARGET=x86_64-linux-gnu   ;;
    x86_64-linux-musl)    ZIG_TARGET=x86_64-linux-musl  ;;
    aarch64-linux-gnu)    ZIG_TARGET=aarch64-linux-gnu  ;;
    aarch64-linux-musl)   ZIG_TARGET=aarch64-linux-musl ;;
    x86_64-apple-darwin*) ZIG_TARGET=x86_64-macos       ;;
    aarch64-apple-darwin*) ZIG_TARGET=aarch64-macos     ;;
    *) echo "unsupported target ${target}" >&2; exit 1 ;;
esac

# Seed the Zig package cache from the checkout we were given, so that the lazy
# `libgit2` dependency resolves with the sandbox offline. `zig fetch` hashes the
# tree, and it prints the hash it computed — which must be the one build.zig.zon
# pins, or the build below would try to reach the network and fail. Checking it
# here turns that into one legible error instead.
LIBGIT2_HASH="N-V-__8AAPAkMAHF73yNJSpdsQlf-mNs4jTb0NHpLoiNRzOw"
# Zig hashes everything in the directory, `.git` included, and a GitSource
# arrives with one. Leaving it in changes the hash — it is what the check below
# caught the first time this recipe ran.
rm -rf "${WORKSPACE}/srcdir/libgit2/.git"
cd Ajt.jl
fetched="$(zig fetch "${WORKSPACE}/srcdir/libgit2")"
if [ "${fetched}" != "${LIBGIT2_HASH}" ]; then
    echo "libgit2 hashed to ${fetched}, but build.zig.zon pins ${LIBGIT2_HASH}" >&2
    exit 1
fi

zig build \
    -Dtarget="${ZIG_TARGET}" \
    -Doptimize=ReleaseFast \
    -Dgit \
    --prefix "${prefix}"

install_license LICENSE

# libgit2 is GPL-2.0-with-linking-exception and -Dgit links it in statically.
# The exception permits the linking; it does not excuse shipping without the
# notice. Identified by its contents rather than by its path: the unpacked
# dependency is named by hash, and it contains several COPYING files -- the
# first one `find` returns is bundled PCRE's, which is not the notice owed here.
for candidate in $(find . -path '*zig-pkg*' -name COPYING); do
    if grep -q 'libgit2 is Copyright' "${candidate}"; then
        install_license "${candidate}"
        found_libgit2_licence=1
        break
    fi
done
if [ -z "${found_libgit2_licence:-}" ]; then
    echo "libgit2 was linked in but its licence was not found to ship with it" >&2
    exit 1
fi
"""

# Only what the release binaries already cover, and only what has actually been
# run. Windows is absent on purpose: three call sites in Ajt need porting and a
# fourth failure is in Zig 0.16.0's own std, which cannot be fixed from here.
platforms = [
    Platform("x86_64", "linux"; libc = "glibc"),
    Platform("x86_64", "linux"; libc = "musl"),
    Platform("aarch64", "linux"; libc = "glibc"),
    Platform("aarch64", "linux"; libc = "musl"),
    Platform("x86_64", "macos"),
    Platform("aarch64", "macos"),
]

products = [
    ExecutableProduct("ajt", :ajt),
]

dependencies = Dependency[]

build_tarballs(
    ARGS, name, version, sources, script, platforms, products, dependencies;
    julia_compat = "1.12",
)
